import "../styles/globals.css";
import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        {/* Global Header */}
        <header className="top-nav">
          <div className="nav-left">SHUBHAM GOEL</div>
          <nav className="nav-right">
            <Link href="/projects" className="nav-link">MY PROJECTS</Link>
            <Link href="/about" className="nav-link">ABOUT ME</Link>
            <Link href="#socials" className="nav-link">SOCIALS</Link>
          </nav>
        </header>

        {/* Page Content */}
        <div className="layout-container">{children}</div>
      </body>
    </html>
  );
}